"""Initial_PostgreSQL_Schema

Revision ID: 999bc71291f9
Revises: 
Create Date: 2026-08-05 21:18:04.201276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999bc71291f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'prediction_history', 'predictions', ['prediction_id'], ['id'])
    op.alter_column('predictions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictions', 'prediction_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('price_recommendations', 'forecasted_demand',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_recommendations', 'forecasted_demand',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predictions', 'prediction_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'prediction_history', type_='foreignkey')
    # ### end Alembic commands ###
