import React from 'react';
import { FileText, Download, TrendingUp, ShieldCheck, Sparkles, CheckCircle2 } from 'lucide-react';

const ReportsPage = () => {
  const reportsList = [
    { title: 'Executive Summary Report — Q3 2026', type: 'PDF Document', size: '2.4 MB', date: 'Jul 29, 2026', status: 'Ready' },
    { title: 'Dynamic Pricing Policy Benchmark', type: 'CSV Data', size: '1.1 MB', date: 'Jul 28, 2026', status: 'Ready' },
    { title: 'Extra Trees Model Validation Audit', type: 'PDF Document', size: '4.8 MB', date: 'Jul 25, 2026', status: 'Ready' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="pb-4 border-b border-slate-800">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-300 text-xs font-semibold mb-2">
          <FileText className="w-3.5 h-3.5 text-blue-400" /> Business Intelligence & Policy Generator
        </div>
        <h1 className="text-2xl lg:text-3xl font-extrabold text-white">
          Executive Reports & <span className="gradient-text">Pricing Policies</span>
        </h1>
        <p className="text-xs text-slate-400">
          Automated reporting hub for business stakeholders, dynamic pricing policy rules, and strategy documents.
        </p>
      </div>

      {/* Dynamic Pricing Recommendation Policy Card */}
      <div className="rounded-3xl glass-card p-6 lg:p-8 border border-purple-500/30 bg-gradient-to-r from-blue-950/30 via-purple-950/30 to-slate-950/60 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-purple-500/20 text-purple-300 border border-purple-500/30">
              <Sparkles className="w-6 h-6 text-amber-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">AI Dynamic Pricing Policy Policy v1.0</h3>
              <p className="text-xs text-slate-400">Generated by Extra Trees ML Regressor (R²: 0.6742)</p>
            </div>
          </div>
          <span className="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-bold font-mono">
            Active Strategy
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium">Margin Multiplier Rule</span>
            <p className="text-sm font-bold text-white mt-1">High Freight Impact (+18.5%)</p>
            <p className="text-[11px] text-slate-500 mt-1">Adjusts valuation when freight value &gt; $20.00</p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium">Volume Weighting</span>
            <p className="text-sm font-bold text-purple-300 mt-1">Bulk Dimension Pricing</p>
            <p className="text-[11px] text-slate-500 mt-1">Calculates cubic volume factor (&gt;10,000 cm³)</p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium">Confidence Floor</span>
            <p className="text-sm font-bold text-emerald-400 mt-1">94.0% Minimum Floor</p>
            <p className="text-[11px] text-slate-500 mt-1">Ensures tight valuation spread across samples</p>
          </div>
        </div>
      </div>

      {/* Reports Download List */}
      <div className="rounded-3xl glass-card border border-slate-800 p-6">
        <h3 className="text-base font-bold text-white mb-4">Available Strategy Reports</h3>
        
        <div className="space-y-3">
          {reportsList.map((r, i) => (
            <div key={i} className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800 flex items-center justify-between hover:bg-slate-800/40 transition">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/20">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-white">{r.title}</h4>
                  <p className="text-[11px] text-slate-400">{r.type} • {r.size} • Generated {r.date}</p>
                </div>
              </div>

              <button
                onClick={() => alert(`Downloading report: ${r.title}`)}
                className="flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-800 hover:bg-purple-600 text-slate-300 hover:text-white font-bold text-xs transition"
              >
                <Download className="w-4 h-4" /> Download
              </button>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};

export default ReportsPage;
